services:
  jaeger:
    image: jaegertracing/all-in-one:1.53 # Use Jaeger all-in-one container image version 1.53
    container_name: jaegertracing # Set the container name to jaegertracing
    ports:
      - "6831:6831/udp" # Jaeger Thrift Compact over UDP port for client reporting
      - "6832:6832/udp" # Jaeger Thrift Binary over UDP port for client reporting
      - "5778:5778" # Port for Jaeger agent's config server
      - "16686:16686" # Port for Jaeger UI
      - "4317:4317" # OTLP gRPC port for receiving traces and metrics
      - "4318:4318" # OTLP HTTP port for receiving traces and metrics
      - "14250:14250" # gRPC port for Jaeger collector service
      - "14268:14268" # HTTP port for Jaeger collector service
      - "14269:14269" # HTTP port for Jaeger collector's health check
      - "9411:9411" # Zipkin collector port
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411 # Enable Zipkin HTTP collector on port 9411
      - COLLECTOR_OTLP_ENABLED=true # Enable OTLP collector
